export const countries = [
  {code: "93", name: "Afeganistão", initial: "AF" },
  {code: "27", name: "África do Sul", initial: "ZA" },
  {code: "355", name: "Albânia", initial: "AL" },
  {code: "49", name: "Alemanha", initial: "DE" },
  {code: "376", name: "Andorra", initial: "AD" },
  {code: "244", name: "Angola", initial: "AO" },
  {code: "1264", name: "Anguila", initial: "AI" },
  {code: "672", name: "Antártida", initial: "AQ" },
  {code: "1268", name: "Antígua e Barbuda", initial: "AG" },
  {code: "599", name: "Antilhas Holandesas", initial: "AN" },
  {code: "966", name: "Arábia Saudita", initial: "SA" },
  {code: "213", name: "Argélia", initial: "DZ" },
  {code: "54", name: "Argentina", initial: "AR" },
  {code: "374", name: "Armênia", initial: "AM" },
  {code: "297", name: "Aruba", initial: "AW" },
  {code: "61", name: "Austrália", initial: "AU" },
  {code: "43", name: "Áustria", initial: "AT" },
  {code: "", name: "Autoridade Palestina", initial: "PS" },
  {code: "994", name: "Azerbaijão", initial: "AZ" },
  {code: "1242", name: "Bahamas", initial: "BS" },
  {code: "973", name: "Bahrein", initial: "BH" },
  {code: "880", name: "Bangladesh", initial: "BD" },
  {code: "1246", name: "Barbados", initial: "BB" },
  {code: "375", name: "Belarus", initial: "BY" },
  {code: "32", name: "Bélgica", initial: "BE" },
  {code: "501", name: "Belize", initial: "BZ" },
  {code: "229", name: "Benin", initial: "BJ" },
  {code: "1441", name: "Bermuda", initial: "BM" },
  {code: "591", name: "Bolívia", initial: "BO" },
  {code: "387", name: "Bósnia e Herzegovina", initial: "BA" },
  {code: "267", name: "Botsuana", initial: "BW" },
  {code: "55", name: "Brasil", initial: "BR" },
  {code: "673", name: "Brunei", initial: "BN" },
  {code: "359", name: "Bulgária", initial: "BG" },
  {code: "226", name: "Burquina Faso", initial: "BF" },
  {code: "257", name: "Burundi", initial: "BI" },
  {code: "975", name: "Butão", initial: "BT" },
  {code: "238", name: "Cabo Verde", initial: "CV" },
  {code: "237", name: "Camarões", initial: "CM" },
  {code: "855", name: "Camboja", initial: "KH" },
  {code: "1", name: "Canadá", initial: "CA" },
  {code: "974", name: "Catar", initial: "QA" },
  {code: "7", name: "Cazaquistão", initial: "KZ" },
  {code: "235", name: "Chade", initial: "TD" },
  {code: "56", name: "Chile", initial: "CL" },
  {code: "86", name: "China", initial: "CN" },
  {code: "357", name: "Chipre", initial: "CY" },
  {code: "39", name: "Cidade do Vaticano", initial: "VA" },
  {code: "65", name: "Cingapura", initial: "SG" },
  {code: "57", name: "Colômbia", initial: "CO" },
  {code: "269", name: "Comoros", initial: "KM" },
  {code: "242", name: "Congo", initial: "CG" },
  {code: "243", name: "Congo, República Democrática do", initial: "CD" },
  {code: "82", name: "Coreia", initial: "KR" },
  {code: "850", name: "Coreia do Norte", initial: "KP" },
  {code: "506", name: "Costa Rica", initial: "CR" },
  {code: "225", name: "Côte d'Ivoire (Costa do Marfim)", initial: "CI" },
  {code: "385", name: "Croácia", initial: "HR" },
  {code: "53", name: "Cuba", initial: "CU" },
  {code: "45", name: "Dinamarca", initial: "DK" },
  {code: "253", name: "Djibuti", initial: "DJ" },
  {code: "1767", name: "Dominica", initial: "DM" },
  {code: "20", name: "Egito", initial: "EG" },
  {code: "503", name: "El Salvador", initial: "SV" },
  {code: "971", name: "Emirados Árabes Unidos", initial: "AE" },
  {code: "593", name: "Equador", initial: "EC" },
  {code: "291", name: "Eritreia", initial: "ER" },
  {code: "421", name: "Eslováquia", initial: "SK" },
  {code: "386", name: "Eslovênia", initial: "SI" },
  {code: "34", name: "Espanha", initial: "ES" },
  {code: "1", name: "Estados Unidos", initial: "US" },
  {code: "372", name: "Estônia", initial: "EE" },
  {code: "251", name: "Etiópia", initial: "ET" },
  {code: "63", name: "Filipinas", initial: "PH" },
  {code: "358", name: "Finlândia", initial: "FI" },
  {code: "33", name: "França", initial: "FR" },
  {code: "241", name: "Gabão", initial: "GA" },
  {code: "220", name: "Gâmbia", initial: "GM" },
  {code: "233", name: "Gana", initial: "GH" },
  {code: "995", name: "Geórgia", initial: "GE" },
  {code: "", name: "Geórgia do Sul e Ilhas Sandwich do Sul", initial: "GS" },
  {code: "350", name: "Gibraltar", initial: "GI" },
  {code: "1473", name: "Granada", initial: "GD" },
  {code: "30", name: "Grécia", initial: "GR" },
  {code: "299", name: "Groenlândia", initial: "GL" },
  {code: "", name: "Guadalupe", initial: "GP" },
  {code: "1671", name: "Guam", initial: "GU" },
  {code: "502", name: "Guatemala", initial: "GT" },
  {code: "", name: "Guernsey", initial: "GG" },
  {code: "592", name: "Guiana", initial: "GY" },
  {code: "", name: "Guiana Francesa", initial: "GF" },
  {code: "224", name: "Guiné", initial: "GN" },
  {code: "240", name: "Guiné Equatorial", initial: "GQ" },
  {code: "245", name: "Guiné-Bissau", initial: "GW" },
  {code: "509", name: "Haiti", initial: "HT" },
  {code: "504", name: "Honduras", initial: "HN" },
  {code: "852", name: "Hong Kong S. A. R", initial: "HK" },
  {code: "36", name: "Hungria", initial: "HU" },
  {code: "967", name: "Iêmen", initial: "YE" },
  {code: "", name: "Ilha Bouvet", initial: "BV" },
  {code: "61", name: "Ilha Christmas", initial: "CX" },
  {code: "44", name: "Ilha de Man", initial: "IM" },
  {code: "672", name: "Ilha Norfolk", initial: "NF" },
  {code: "1345", name: "Ilhas Cayman", initial: "KY" },
  {code: "61", name: "Ilhas Cocos (Keeling)", initial: "CC" },
  {code: "682", name: "Ilhas Cook", initial: "CK" },
  {code: "298", name: "Ilhas Faroés", initial: "FO" },
  {code: "679", name: "Ilhas Fiji", initial: "FJ" },
  {code: "", name: "Ilhas Heard e Ilhas McDonald", initial: "HM" },
  {code: "500", name: "Ilhas Malvinas (Falkland Islands)", initial: "FK" },
  {code: "1670", name: "Ilhas Marianas do Norte", initial: "MP" },
  {code: "692", name: "Ilhas Marshall", initial: "MH" },
  {code: "677", name: "Ilhas Salomão", initial: "SB" },
  {code: "1649", name: "Ilhas Turks e Caicos", initial: "TC" },
  {code: "1340", name: "Ilhas Virgens Americanas", initial: "VI" },
  {code: "1284", name: "Ilhas Virgens Britânicas", initial: "VG" },
  {code: "91", name: "Índia", initial: "IN" },
  {code: "62", name: "Indonésia", initial: "ID" },
  {code: "98", name: "Irã", initial: "IR" },
  {code: "964", name: "Iraque", initial: "IQ" },
  {code: "353", name: "Irlanda", initial: "IE" },
  {code: "354", name: "Islândia", initial: "IS" },
  {code: "972", name: "Israel", initial: "IL" },
  {code: "39", name: "Itália", initial: "IT" },
  {code: "1876", name: "Jamaica", initial: "JM" },
  {code: "81", name: "Japão", initial: "JP" },
  {code: "", name: "Jersey", initial: "JE" },
  {code: "962", name: "Jordânia", initial: "JO" },
  {code: "686", name: "Kiribati", initial: "KI" },
  {code: "965", name: "Kuaite", initial: "KW" },
  {code: "856", name: "Laos", initial: "LA" },
  {code: "266", name: "Lesoto", initial: "LS" },
  {code: "", name: "Letônia", initial: "LV" },
  {code: "961", name: "Líbano", initial: "LB" },
  {code: "231", name: "Libéria", initial: "LR" },
  {code: "218", name: "Líbia", initial: "LY" },
  {code: "423", name: "Liechtenstein", initial: "LI" },
  {code: "370", name: "Lituânia", initial: "LT" },
  {code: "352", name: "Luxemburgo", initial: "LU" },
  {
code: "389",
 name: "Macedônia, Antiga República Iugoslava da",
    initial: "MK",
  },
  {code: "261", name: "Madagascar", initial: "MG" },
  {code: "60", name: "Malásia", initial: "MY" },
  {code: "265", name: "Malaui", initial: "MW" },
  {code: "960", name: "Maldivas", initial: "MV" },
  {code: "223", name: "Mali", initial: "ML" },
  {code: "356", name: "Malta", initial: "MT" },
  {code: "212", name: "Marrocos", initial: "MA" },
  {code: "", name: "Martinica", initial: "MQ" },
  {code: "230", name: "Maurício", initial: "MU" },
  {code: "222", name: "Mauritânia", initial: "MR" },
  {code: "262", name: "Mayotte", initial: "YT" },
  {code: "52", name: "México", initial: "MX" },
  {code: "691", name: "Micronésia", initial: "FM" },
  {code: "258", name: "Moçambique", initial: "MZ" },
  {code: "373", name: "Moldova", initial: "MD" },
  {code: "377", name: "Mônaco", initial: "MC" },
  {code: "976", name: "Mongólia", initial: "MN" },
  {code: "382", name: "Montenegro", initial: "ME" },
  {code: "1664", name: "Montserrat", initial: "MS" },
  {code: "95", name: "Myanma", initial: "MM" },
  {code: "264", name: "Namíbia", initial: "NA" },
  {code: "674", name: "Nauru", initial: "NR" },
  {code: "977", name: "Nepal", initial: "NP" },
  {code: "505", name: "Nicarágua", initial: "NI" },
  {code: "227", name: "Níger", initial: "NE" },
  {code: "234", name: "Nigéria", initial: "NG" },
  {code: "683", name: "Niue", initial: "NU" },
  {code: "47", name: "Noruega", initial: "NO" },
  {code: "687", name: "Nova Caledônia", initial: "NC" },
  {code: "64", name: "Nova Zelândia", initial: "NZ" },
  {code: "968", name: "Omã", initial: "OM" },
  {code: "31", name: "Países Baixos", initial: "NL" },
  {code: "680", name: "Palau", initial: "PW" },
  {code: "507", name: "Panamá", initial: "PA" },
  {code: "675", name: "Papua-Nova Guiné", initial: "PG" },
  {code: "92", name: "Paquistão", initial: "PK" },
  {code: "595", name: "Paraguai", initial: "PY" },
  {code: "51", name: "Peru", initial: "PE" },
  {code: "870", name: "Pitcairn", initial: "PN" },
  {code: "689", name: "Polinésia Francesa", initial: "PF" },
  {code: "48", name: "Polônia", initial: "PL" },
  {code: "1", name: "Porto Rico", initial: "PR" },
  {code: "351", name: "Portugal", initial: "PT" },
  {code: "254", name: "Quênia", initial: "KE" },
  {code: "996", name: "Quirguistão", initial: "KG" },
  {code: "853", name: "RAE de Macau", initial: "MO" },
  {code: "44", name: "Reino Unido", initial: "UK" },
  {code: "236", name: "República Centro-Africana", initial: "CF" },
  {code: "1809", name: "República Dominicana", initial: "DO" },
  {code: "420", name: "República Tcheca", initial: "CZ" },
  {code: "", name: "Reunião", initial: "RE" },
  {code: "40", name: "Romênia", initial: "RO" },
  {code: "250", name: "Ruanda", initial: "RW" },
  {code: "7", name: "Rússia", initial: "RU" },
  {code: "508", name: "Saint-Pierre e Miquelon", initial: "PM" },
  {code: "685", name: "Samoa", initial: "WS" },
  {code: "1684", name: "Samoa Americana", initial: "AS" },
  {code: "378", name: "San Marino", initial: "SM" },
  {code: "290", name: "Santa Helena", initial: "SH" },
  {code: "1758", name: "Santa Lúcia", initial: "LC" },
  {code: "239", name: "São Tomé e Príncipe", initial: "ST" },
  {code: "1784", name: "São Vicente e Granadinas", initial: "VC" },
  {code: "248", name: "Seicheles", initial: "SC" },
  {code: "221", name: "Senegal", initial: "SN" },
  {code: "232", name: "Serra Leoa", initial: "SL" },
  {code: "381", name: "Sérvia", initial: "RS" },
  {code: "963", name: "Síria", initial: "SY" },
  {code: "252", name: "Somália", initial: "SO" },
  {code: "94", name: "Sri Lanka", initial: "LK" },
  {code: "1869", name: "St. Kitts e Névis", initial: "KN" },
  {code: "268", name: "Suazilândia", initial: "SZ" },
  {code: "249", name: "Sudão", initial: "SD" },
  {code: "46", name: "Suécia", initial: "SE" },
  {code: "41", name: "Suíça", initial: "CH" },
  {code: "597", name: "Suriname", initial: "SR" },
  {code: "", name: "Svalbard", initial: "SJ" },
  {code: "992", name: "Tagiquistão", initial: "TJ" },
  {code: "66", name: "Tailândia", initial: "TH" },
  {code: "886", name: "Taiwan", initial: "TW" },
  {code: "255", name: "Tanzânia", initial: "TZ" },
  {
code: "",
 name: "Terras Austrais e Antárticas Francesas",
    initial: "TF",
  },
  {
code: "",
 name: "Território Britânico do Oceano Índico",
    initial: "IO",
  },
  {code: "", name: "Territórios Insulares dos EUA", initial: "UM" },
  {code: "670", name: "Timor Leste", initial: "TP" },
  {code: "228", name: "Togo", initial: "TG" },
  {code: "690", name: "Tokelau", initial: "TK" },
  {code: "676", name: "Tonga", initial: "TO" },
  {code: "1868", name: "Trinidad e Tobago", initial: "TT" },
  {code: "216", name: "Tunísia", initial: "TN" },
  {code: "993", name: "Turcomenistão", initial: "TM" },
  {code: "90", name: "Turquia", initial: "TR" },
  {code: "688", name: "Tuvalu", initial: "TV" },
  {code: "380", name: "Ucrânia", initial: "UA" },
  {code: "256", name: "Uganda", initial: "UG" },
  {code: "598", name: "Uruguai", initial: "UY" },
  {code: "998", name: "Uzbequistão", initial: "UZ" },
  {code: "678", name: "Vanuatu", initial: "VU" },
  {code: "58", name: "Venezuela", initial: "VE" },
  {code: "84", name: "Vietnã", initial: "VN" },
  {code: "681", name: "Wallis e Futuna", initial: "WF" },
  {code: "260", name: "Zâmbia", initial: "ZM" },
  {code: "263", name: "Zimbábue", initial: "ZW" },
];
